security:
    encoders:
        Mariage\UserBundle\Entity\User: sha512

    providers:
        main:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN:    ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key:    %secret%
