mariage_guest_homepage:
    path:     /guests
    defaults: { _controller: MariageGuestBundle:Guest:index }


mariage_guest_add:
    path:     /add_guest
    defaults: { _controller: MariageGuestBundle:Guest:addGuest }


mariage_guest_remove:
    path:     /remove_guest/{id}
    defaults: { _controller: MariageGuestBundle:Guest:removeGuest }
    requirements:
        id: \d+


mariage_guest_edit:
    path:     /edit_guest/{id}
    defaults: { _controller: MariageGuestBundle:Guest:editGuest }
    requirements:
        id: \d+


mariage_guest_organization:
    path:    /organization
    defaults: { _controller: MariageGuestBundle:Guest:organization }


mariage_guest_message:
    path:    /message
    defaults: { _controller: MariageGuestBundle:Message:addMessage }



mariage_guest_music:
    path:    /musics
    defaults: { _controller: MariageGuestBundle:Music:music }


mariage_guest_addMusic:
    path:    /add_music
    defaults: { _controller: MariageGuestBundle:Music:addMusic }


mariage_guest_removeMusic:
    path:     /remove_music/{id}
    defaults: { _controller: MariageGuestBundle:Music:removeMusic }
    requirements:
        id: \d+


mariage_guest_editMusic:
    path:     /edit_music/{id}
    defaults: { _controller: MariageGuestBundle:Music:editMusic }
    requirements:
        id: \d+